# .github/workflows/netlify.yml
name: Build and Deploy module2 to Netlify
on:
  push:
    branches:
      - main
    paths:
      - 'apps/module2/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install packages
        run: rm -rf node_modules && yarn install

      - name: Build module2
        run: yarn nx build module2

      - name: Deploy module2 to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './dist/apps/module2'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy module2 from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
          netlify-config-path: './apps/module2/src/netlify.toml'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_MODULE2_SITE_ID }}
        timeout-minutes: 1
